### ISSUE TITLE
Unable to run autoripy

### ISSUE THREAD

**Issue by dark6naw** [Silv3rHorn/autoripy#1]
Hi yk,

I am unable to run autoripy, I have put autoripy in the same folder as regripper and this is the command that I ran on an extracted registry hive in a directory

python autoripy -rr C:\Users\XXX\Desktop\Regripper -s C:\Users\XXX\Desktop\registry -c all

Am I doing it right? kindly advise.

Thank you.

**Comment by Silv3rHorn** [comment]
Hi,

Please use `--rr` instead of `-rr`. If that still fails, please provide me with the generated error messages and log file. Thanks.

**Comment by dark6naw** [comment]
Hi,

Alright --rr works, this is the message that I get.

[_autoripy_log.2018-01-22@160557.txt](https://github.com/Silv3rHorn/autoripy/files/1651164/_autoripy_log.2018-01-22.160557.txt)
![error](https://user-images.githubusercontent.com/34785594/35210747-6d6bc468-ff8e-11e7-85a6-bd15847798c3.png)

Thank you for your help!

**Comment by Silv3rHorn** [comment]
Just want to make sure, is the provided error message obtained after using `--rr` or before?

**Comment by dark6naw** [comment]
its using --rr

**Comment by Silv3rHorn** [comment]
I couldn't reproduce your error even after copying autoripy, regripper, and registry hives to my desktop. May I know if you have installed Perl, and the Perl module `Parse::Win32Registry`?

**Comment by dark6naw** [comment]
That could be a possibility because I am using strawberry perl. let me try it tomorrow and let you know if it works. Thank you!

**Comment by Silv3rHorn** [comment]
I am using Strawberry Perl too, so that shouldn't be the issue. 

Another possibility is that `rip.pl` is missing from your regripper folder. Could you check for that?

**Comment by dark6naw** [comment]
Yup rip.pl is in the same folder. I did some troubleshooting and realised that Strawberry perl was not installed properly. Its working now. Thank you!

**Comment by Silv3rHorn** [comment]
Good to know!
