### ISSUE TITLE
New release version of "autoripy" (v20200827) generating errors upon execution.

### ISSUE THREAD

**Issue by CmdrBurrito** [Silv3rHorn/autoripy#2]
**Hi, I'm getting the following error when I attempt to run the newly released "autoripy" (v20200827) executable:**

C:\IRTools\RegRipper3.0>autoripy-20200827.exe
Traceback (most recent call last):
  File "autoripy.py", line 105, in <module>
  File "autoripy.py", line 89, in main
  File "plugin_selector.py", line 184, in get_selection
  File "plugin_selector.py", line 22, in _validate_input
  File "ntpath.py", line 78, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
[5648] Failed to execute script autoripy

**Also, when I attempt to execute the newly released .py version of the tool, I get the (similar) error:**

C:\IRTools\RegRipper3.0\autoripy-20200827>autoripy.py
Traceback (most recent call last):
  File "C:\IRTools\RegRipper3.0\autoripy-20200827\autoripy.py", line 105, in <module>
    if not main():
  File "C:\IRTools\RegRipper3.0\autoripy-20200827\autoripy.py", line 89, in main
    options = ps.get_selection()
  File "C:\IRTools\RegRipper3.0\autoripy-20200827\plugin_selector.py", line 184, in get_selection
    if not _validate_input(options):
  File "C:\IRTools\RegRipper3.0\autoripy-20200827\plugin_selector.py", line 22, in _validate_input
    if not os.path.isfile(os.path.join(options.rr, u'rip.exe')):
  File "C:\Python\Python38\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Looks like some kind of bug to me.  However, it is interesting to note that executing either the .exe or the .py with an incorrect parameter, or with the "-h" parameter, does result in the correct "Usage" message being displayed.  For example:**  

C:\IRTools\RegRipper3.0>autoripy-20200827.exe -h
usage: autoripy-20200827.exe [-h] [-s SYSTEM] [-a AMCACHE] [-n NTUSER] [-u USRCLASS] [-m MULTIPLE] [-r REPORTDIR] [-c CAT] [rr]

autoripy is an attempt to replicate the functions of auto_rip by Corey Harrell in Python.
auto_rip automates the execution of RegRipper according to an examination process.
auto_rip is a Copyright of Corey Harrell (jIIr).

Supported Categories:
         all             gets information from all categories
         os              gets General Operating System Information
         users           gets User Account Information
         software        gets Installed Software Information
         network         gets Networking Configuration Information
         storage         gets Storage Information
         device          gets Device Information
         execution       gets Program Execution Information
         autoruns        gets Autostart Locations Information
         log             gets Logging Information
         malware         gets Malware Indicators
         web             gets Web Browsing Information
         user_config     gets User Account Configuration Information
         user_act        gets User Account General Activity
         user_network    gets User Account Network Activity
         user_file       gets User Account File/Folder Access Activity
         user_virtual    gets User Account Virtualization Access Activity
         comm            Communication Software Information

Usage:
         Extract all information from the SAM, Security, Software, and System hives.
         autoripy C:\regripper -s H:\Windows\System32\config -c all

         Extract file access information from NTUSER.DAT and UsrClass.dat hive (Windows 7 profile)
         autoripy C:\regripper -n H:\Users\Corey -u H:\Users\Corey\AppData\Local\Microsoft\Windows -c user_file

         Extract all information from all Windows registry hives without using -c switch.
         autoripy C:\regripper -s H:\Windows\System32\config -a H:\Windows\AppCompat\Programs -n H:\Users\Corey -u H:\Users\Corey\AppData\Local\Microsoft\Windows

         Extract all information from the SAM, Security, Software and System hives, then store output reports in a specified directory.
         autoripy C:\regripper -s H:\Windows\System32\config -r C:\reports

         Extract all information from the SAM, Security, Software and System hives, NTUSER.DAT and UsrClass.dat from each user in separate directories, then store output reports in a specified directory.
         autoripy C:\regripper -s H:\hives -m H:\hives\Users -r C:\reports

positional arguments:
  rr                    path to the folder containing RegRipper.

optional arguments:
  -h, --help            show this help message and exit
  -s SYSTEM, --system SYSTEM
                        path to the folder containing the SAM, Security, Software, and System hives.
  -a AMCACHE, --amcache AMCACHE
                        path to the folder containing the Amcache.hve hive.
  -n NTUSER, --ntuser NTUSER
                        path to the folder containing the NTUSER.DAT hive.
  -u USRCLASS, --usrclass USRCLASS
                        path to the folder containing the UsrClass.dat hive.
  -m MULTIPLE, --multiple MULTIPLE
                        path to the folder containing multiple <User>\NTUSER.DAT and/or <User>\UsrClass.DAT.
  -r REPORTDIR, --reportdir REPORTDIR
                        path to the folder to store the output reports.
  -c CAT, --cat CAT     specifies the plugin categories to run. Separate multiple categories with a comma.

**...or...**

C:\IRTools\RegRipper3.0>autoripy-20200827.exe -?
usage: autoripy-20200827.exe [-h] [-s SYSTEM] [-a AMCACHE] [-n NTUSER] [-u USRCLASS] [-m MULTIPLE] [-r REPORTDIR]
                             [-c CAT]
                             [rr]
autoripy-20200827.exe: error: unrecognized arguments: -?

**Comment by Silv3rHorn** [comment]
My bad, I forgot to perform input validation for the compulsory argument (i.e. path to the RegRipper directory). This had been fixed now and the release executable had been updated. Pls try again.

**Comment by CmdrBurrito** [comment]
Just tried it, and it's working as expected now.  Many thanks!
