### ISSUE TITLE
Perchance can a new/updated version of "autoripy.exe" be generated and posted?

### ISSUE THREAD

**Issue by CmdrBurrito** [Silv3rHorn/autoripy#4]
Is this a dead project, or perchance could a new compiled version of "autoripy.exe" for Windows, which uses all of the latest RegRipper 3.0 plugins, be generated and posted here?

**Comment by Silv3rHorn** [comment]
Hi @CmdrBurrito , really appreciate your continuous support of this tool. I have updated the latest release with the recently added RegRipper 3.0 plugins.

Regards, 
Silv3rHorn

**Comment by CmdrBurrito** [comment]
Awesome!  Many thanks!
